repository_type: pipeline

nf_core_version: 3.5.1

lint:
  files_unchanged:
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-lah_logo_light.png
    - docs/images/nf-core-lah_logo_light.png
    - docs/images/nf-core-lah_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CODE_OF_CONDUCT.md
    - assets/nf-core-lah_logo_light.png
    - docs/images/nf-core-lah_logo_light.png
    - docs/images/nf-core-lah_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: BIKRAFT
  name: LAH
  description: Starting template
  author: Preecha Patumcharoenpol
  version: 0.0.1
  force: true
  outdir: .
  skip_features:
    - igenomes
    - gpu
    - codespaces
    - adaptivecard
    - slackreport
  is_nfcore: false
